name: Build for macOS (aarch64)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-macos:
    name: Build macOS (aarch64)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust (aarch64 target)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true

      - name: Install dependencies
        run: |
          brew install cmake
          rustup target add aarch64-apple-darwin

      - name: Build for macOS
        run: |
          cargo build --target=aarch64-apple-darwin --release

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: target/aarch64-apple-darwin/release/fighter
